# Generated by Django 2.0.3 on 2018-05-24 00:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='histogram',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
