version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.celery
    ports:
      - "8000:8000"
    command: /start.sh

  webpack:
    build:
      context: .
      dockerfile: ./compose/local/webpack/Dockerfile
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.webpack
    ports:
      - "8080:8080"
    command: /start-webpack.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  redis:
    image: redis:3.0

  cantaloupe:
    build:
      context: .
      dockerfile: ./compose/local/cantaloupe/Dockerfile
    volumes:
      - ./media/iiif:/var/lib/cantaloupe/images
    ports:
      - "8182:8182"

  celeryworker:
    <<: *django
    depends_on:
      - redis
      - postgres
      - mailhog
    env_file:
      - ./.envs/.local/.celery
      - ./.envs/.local/.postgres
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    <<: *django
    depends_on:
      - redis
      - postgres
      - mailhog
    env_file:
      - ./.envs/.local/.celery
      - ./.envs/.local/.postgres
    ports: []
    command: /start-celerybeat.sh
